apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher-app
  template:
    metadata:
      labels:
        app: rancher-app
    spec:
      containers:
      - name: rancher-container
        image: anandnanwana14/rancher-cicd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-service
spec:
  selector:
    app: rancher-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
